name: Deploy On Azure 🚀

on: 
    workflow_dispatch:
    push:
        branches:
            - ReleaseCIDI


env:
    DOTNET_VERSION: '6.0.x'
    AZURE_WEBAPP_PACKAGE_PATH: './PasswordManagement'
 
jobs:
    publish:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            
            - name: Setup .Net
              uses: actions/setup-dotnet@v4
              with:
               dotnet-version: ${{ env.DOTNET_VERSION }}

            - name: Restore
              run: dotnet restore ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
            
            - name: Build
              run: dotnet build ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} --configuration Release --no-restore
            
            - name: Publish
              run: dotnet publish ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} --configuration Release --no-build

